config/routes.rb
Rails.application.routes.draw do

  root 'results#home'
  resources :results
  get 'ratings' => 'results#new'
  post 'results' => 'results#create'

  get 'new_wrestler' => 'wrestler#new'
  post 'wres_results' => 'wrestler#show'
  post 'wres_save' => 'wrestler#save'
  get 'all_wrestlers' => 'wrestler#index'
  resources :wrestler, only: [:update, :edit, :destroy]

  end

app/models/wrestler.rb
class Wrestler < ActiveRecord::Base

  #Mix in helper
  include ResultsHelper

  # Default scope
  default_scope -> { order('name ASC')}

  # No two wrestlers should be able to have the same name
  validates(:name, presence: true, uniqueness: true)
  

  def calculate_score(execution, ability, psychology)

    # average scores together with the same principles from match star rater but slightly different
    score = (execution + (ability * 3.0) + (psychology * 3.0)) / 7.0

    # reward wrestler if all three traits are strong
    score += 0.25 if execution >= 3.25 && ability >= 3.25 && psychology >= 3.25

    # reward wrestler again if ability and execution are strong
    score += 0.25 if execution >= 3.25 && ability >= 3.25

    #reward wrestler again if psychology and execution are exceptional
    score += 0.25 if execution >= 3.50 && psychology >= 3.50

    #reward wrestler again if all three traits are exceptional. This is an exceptional worker
    score += 0.25 if execution >= 3.50 && psychology >= 3.50 && ability >= 3.50

    #return score
    score
  end
end

app/controllers/wrestler_controller.rb
class WrestlerController < ApplicationController

  include WrestlerHelper

  def new
    @wrestler = Wrestler.new
  end

  def show
    @wrestler = Wrestler.new

    # assign params to instance
    @wrestler.name = params[:wrestler][:name]
    @wrestler.striking = params[:wrestler][:striking]
    @wrestler.slams = params[:wrestler][:slams]
    @wrestler.submission = params[:wrestler][:submission]
    @wrestler.sell_timing = params[:wrestler][:sell_timing]
    @wrestler.mat_and_chain = params[:wrestler][:mat_and_chain]
    @wrestler.transition = params[:wrestler][:transition]
    @wrestler.setting_up = params[:wrestler][:setting_up]
    @wrestler.bumping = params[:wrestler][:bumping]

    @wrestler.technical = params[:wrestler][:technical]
    @wrestler.high_fly = params[:wrestler][:high_fly]
    @wrestler.power = params[:wrestler][:power]
    @wrestler.conditioning = params[:wrestler][:conditioning]
    @wrestler.durability = params[:wrestler][:durability]
    @wrestler.basing = params[:wrestler][:basing]
    @wrestler.reaction_time = params[:wrestler][:reaction_time]

    @wrestler.shine = params[:wrestler][:shine]
    @wrestler.heat = params[:wrestler][:heat]
    @wrestler.ring_awareness = params[:wrestler][:ring_awareness]
    @wrestler.selling = params[:wrestler][:selling]
    @wrestler.comebacks = params[:wrestler][:comebacks]

    @wrestler.execution = execution_score
    @wrestler.ability = ability_score
    @wrestler.psychology = psych_score

    # calculate wrestler score
    @wrestler.score = @wrestler.calculate_score(execution_score, ability_score, psych_score)

    #store star rating
    @wrestler.star_rating = @wrestler.convert_to_star_rating(@wrestler.score)

    # send to results page
    render 'wrestler/wrestler_score'

  end

  def execution_score
    striking = @wrestler.striking.to_f
    slams = @wrestler.slams.to_f
    submission = @wrestler.submission.to_f
    sell_timing = @wrestler.sell_timing.to_f
    mat_and_chain = @wrestler.mat_and_chain.to_f
    transition = @wrestler.transition.to_f
    setting_up = @wrestler.setting_up.to_f
    bumping = @wrestler.bumping.to_f
    (striking + slams + submission + sell_timing + mat_and_chain + transition + setting_up + bumping) / 8.0
  end

  def ability_score
    technical = @wrestler.technical.to_f
    high_fly = @wrestler.high_fly.to_f
    power = @wrestler.power.to_f
    conditioning = @wrestler.conditioning.to_f
    durability = @wrestler.durability.to_f
    basing = @wrestler.basing.to_f
    reaction_time = @wrestler.reaction_time.to_f
    (technical + high_fly + power + conditioning + durability + basing + reaction_time) / 7.0
  end

  def psych_score
    shine = @wrestler.shine.to_f
    heat = @wrestler.heat.to_f
    selling = @wrestler.selling.to_f
    comebacks = @wrestler.comebacks.to_f
    ring_awareness = @wrestler.ring_awareness.to_f
    (shine + heat + selling + comebacks + ring_awareness) / 5.0
  end

  def save
    ActionController::Parameters.permit_all_parameters = true
    @wrestler = Wrestler.new(params[:wrestler])
    @wrestler.save
    redirect_to all_wrestlers_url
  end

  def index
    @wrestlers = Wrestler.all
  end

  def edit
    @wrestler = Wrestler.find_by( :id => params[:id])
  end

  def destroy
    Wrestler.destroy(params[:id])
    redirect_to all_wrestlers_url
  end

  def update
    ActionController::Parameters.permit_all_parameters = true
    @wrestler = Wrestler.find(params[:wrestler][:id])

    # assign params to instance
    @wrestler.name = params[:wrestler][:name]
    @wrestler.striking = params[:wrestler][:striking]
    @wrestler.slams = params[:wrestler][:slams]
    @wrestler.submission = params[:wrestler][:submission]
    @wrestler.sell_timing = params[:wrestler][:sell_timing]
    @wrestler.mat_and_chain = params[:wrestler][:mat_and_chain]
    @wrestler.transition = params[:wrestler][:transition]
    @wrestler.setting_up = params[:wrestler][:setting_up]
    @wrestler.bumping = params[:wrestler][:bumping]

    @wrestler.technical = params[:wrestler][:technical]
    @wrestler.high_fly = params[:wrestler][:high_fly]
    @wrestler.power = params[:wrestler][:power]
    @wrestler.conditioning = params[:wrestler][:conditioning]
    @wrestler.durability = params[:wrestler][:durability]
    @wrestler.basing = params[:wrestler][:basing]
    @wrestler.reaction_time = params[:wrestler][:reaction_time]

    @wrestler.shine = params[:wrestler][:shine]
    @wrestler.heat = params[:wrestler][:heat]
    @wrestler.ring_awareness = params[:wrestler][:ring_awareness]
    @wrestler.selling = params[:wrestler][:selling]
    @wrestler.comebacks = params[:wrestler][:comebacks]

    @wrestler.execution = execution_score
    @wrestler.ability = ability_score
    @wrestler.psychology = psych_score

    # calculate wrestler score
    @wrestler.score = @wrestler.calculate_score(execution_score, ability_score, psych_score)

    #store star rating
    @wrestler.star_rating = @wrestler.convert_to_star_rating(@wrestler.score)

    #save wrestler
    @wrestler.save!
    redirect_to all_wrestlers_url
  end

  private

    def wrestler_params
      params.permit(:wrestler)
    end

end

app/helpers/wrestler_helper.rb
module WrestlerHelper

end

app/views/wrestler/edit.html.erb
<h3><%= link_to "Home", root_path %></h3>
<h1>Edit Wrestler</h1>

<%= form_for @wrestler, url: wrestler_path(@wrestler) do |f| %>
    <%= f.label "Name" %><br>
    <%= f.text_field :name %><br><br>
    <h2>EXECUTION</h2>
    <%= f.label "Striking" %><br>
    <%= f.text_field :striking %><br><br>
    <%= f.label "Submissions" %><br>
    <%= f.text_field :submission %><br><br>
    <%= f.label "Slams and Throws" %><br>
    <%= f.text_field :slams %><br><br>
    <%= f.label "Sell Timing" %><br>
    <%= f.text_field :sell_timing %><br><br>
    <%= f.label "Transitioning and Movement" %><br>
    <%= f.text_field :transition %><br><br>
    <%= f.label "Matt and Chain Wrestling" %><br>
    <%= f.text_field :mat_and_chain %><br><br>
    <%= f.label "Setting Up" %><br>
    <%= f.text_field :setting_up %><br><br>
    <%= f.label "Bumping" %><br>
    <%= f.text_field :bumping %><br><br>

    <h2>ABILITY</h2>
    <%= f.label "Technical Ability" %><br>
    <%= f.text_field :technical %><br><br>
    <%= f.label "High Flying Ability" %><br>
    <%= f.text_field :high_fly %><br><br>
    <%= f.label "Power Move Ability" %><br>
    <%= f.text_field :power %><br><br>
    <%= f.label "Reaction Time" %><br>
    <%= f.text_field :reaction_time %><br><br>
    <%= f.label "Durability/Resilience" %><br>
    <%= f.text_field :durability %><br><br>
    <%= f.label "Conditioning" %><br>
    <%= f.text_field :conditioning %><br><br>
    <%= f.label "Basing" %><br>
    <%= f.text_field :basing %><br><br>

    <h2>RING PSYCHOLOGY</h2>
    <%= f.label "Babyface Shine" %><br>
    <%= f.text_field :shine %><br><br>
    <%= f.label "Heel Heat" %><br>
    <%= f.text_field :heat %><br><br>
    <%= f.label "Comebacks/Hope Spots" %><br>
    <%= f.text_field :comebacks %><br><br>
    <%= f.label "Selling/Facials" %><br>
    <%= f.text_field :selling %><br><br>
    <%= f.label "Ring Awareness/Ring General-ship" %><br>
    <%= f.text_field :ring_awareness %><br><br>

    <%= f.hidden_field :id, value: @wrestler.id %>

    <%= f.submit "Submit" %>
<% end %>

app/views/wrestler/index.html.erb
<% if @wrestlers.any? %>
  <h1>Wrestlers</h1>
  <% @wrestlers.each do |wrestler| %>
      <u><h3><%= wrestler.name %></h3></u>
      <p>Execution: <%= convert_to_star_rating(wrestler.execution) %><br>
        Ability: <%= convert_to_star_rating(wrestler.ability) %><br>
        Psychology: <%= convert_to_star_rating(wrestler.psychology) %><br><br>
        <b>Overall: <%= wrestler.score.round(2)%> (<%= convert_to_star_rating(wrestler.score) %>)</b><br><br>
        <%= link_to "Edit Wrestler", edit_wrestler_path(wrestler) %><br>
        <%= link_to "Delete Wrestler", "wrestler/#{wrestler.id}", method: :delete,
                    data: {confirm: "Are you Sure you want to delete #{wrestler.name}?"} %>
      </p><br>
  <% end %>
<% else %>
    <h1>No wrestlers saved.</h1>
<% end %>
<br><br><br>
<%= link_to "Click here to add a new wrestler", new_wrestler_path %>
<h2><%= link_to "Home", root_path %></h2>

app/views/wrestler/new.html.erb
<h3><%= link_to "Home", root_path %></h3>
<h1>Rate Wrestler</h1>

<%= form_for @wrestler, url: wres_results_path do |f| %>
    <%= f.label "Name" %><br>
    <%= f.text_field :name %><br><br>
    <h2>EXECUTION</h2>
    <%= f.label "Striking" %><br>
    <%= f.text_field :striking %><br><br>
    <%= f.label "Submissions" %><br>
    <%= f.text_field :submission %><br><br>
    <%= f.label "Slams and Throws" %><br>
    <%= f.text_field :slams %><br><br>
    <%= f.label "Sell Timing" %><br>
    <%= f.text_field :sell_timing %><br><br>
    <%= f.label "Transitioning and Movement" %><br>
    <%= f.text_field :transition %><br><br>
    <%= f.label "Matt and Chain Wrestling" %><br>
    <%= f.text_field :mat_and_chain %><br><br>
    <%= f.label "Setting Up" %><br>
    <%= f.text_field :setting_up %><br><br>
    <%= f.label "Bumping" %><br>
    <%= f.text_field :bumping %><br><br>

    <h2>ABILITY</h2>
    <%= f.label "Technical Ability" %><br>
    <%= f.text_field :technical %><br><br>
    <%= f.label "High Flying Ability" %><br>
    <%= f.text_field :high_fly %><br><br>
    <%= f.label "Power Move Ability" %><br>
    <%= f.text_field :power %><br><br>
    <%= f.label "Reaction Time" %><br>
    <%= f.text_field :reaction_time %><br><br>
    <%= f.label "Durability/Resilience" %><br>
    <%= f.text_field :durability %><br><br>
    <%= f.label "Conditioning" %><br>
    <%= f.text_field :conditioning %><br><br>
    <%= f.label "Basing" %><br>
    <%= f.text_field :basing %><br><br>

    <h2>RING PSYCHOLOGY</h2>
    <%= f.label "Babyface Shine" %><br>
    <%= f.text_field :shine %><br><br>
    <%= f.label "Heel Heat" %><br>
    <%= f.text_field :heat %><br><br>
    <%= f.label "Comebacks/Hope Spots" %><br>
    <%= f.text_field :comebacks %><br><br>
    <%= f.label "Selling/Facials" %><br>
    <%= f.text_field :selling %><br><br>
    <%= f.label "Ring Awareness/Ring General-ship" %><br>
    <%= f.text_field :ring_awareness %><br><br>

    <%= f.submit "Submit" %>
<% end %>

app/views/wrestler/wrestler_score.html.erb
<h1><%= @wrestler.name %></h1>
<h3>Execution: <%= @wrestler.convert_to_star_rating(@wrestler.execution) %></h3>
<h3>Ability: <%= @wrestler.convert_to_star_rating(@wrestler.ability) %></h3>
<h3>Psychology: <%= @wrestler.convert_to_star_rating(@wrestler.psychology) %></h3>
<h2>Overall: <%= @wrestler.score.round(2) %></h2>
<h2>Star Rating: <%= @wrestler.star_rating %></h2>

<%= form_for @wrestler, url: wres_save_path do |f|%>
    <%= f.hidden_field :striking, value: @wrestler.striking %>
    <%= f.hidden_field :slams, value: @wrestler.slams %>
    <%= f.hidden_field :submission, value: @wrestler.submission %>
    <%= f.hidden_field :sell_timing, value: @wrestler.sell_timing %>
    <%= f.hidden_field :setting_up, value: @wrestler.setting_up %>
    <%= f.hidden_field :transition, value: @wrestler.transition %>
    <%= f.hidden_field :mat_and_chain, value: @wrestler.mat_and_chain %>
    <%= f.hidden_field :bumping, value: @wrestler.bumping %>
    <%= f.hidden_field :technical, value: @wrestler.technical %>
    <%= f.hidden_field :power, value: @wrestler.power %>
    <%= f.hidden_field :high_fly, value: @wrestler.high_fly %>
    <%= f.hidden_field :durability, value: @wrestler.durability %>
    <%= f.hidden_field :conditioning, value: @wrestler.conditioning %>
    <%= f.hidden_field :basing, value: @wrestler.basing %>
    <%= f.hidden_field :reaction_time, value: @wrestler.reaction_time %>
    <%= f.hidden_field :ability, value: @wrestler.ability %>
    <%= f.hidden_field :shine, value: @wrestler.shine %>
    <%= f.hidden_field :heat, value: @wrestler.heat %>
    <%= f.hidden_field :comebacks, value: @wrestler.comebacks %>
    <%= f.hidden_field :selling, value: @wrestler.selling %>
    <%= f.hidden_field :ring_awareness, value: @wrestler.ring_awareness %>
    <%= f.hidden_field :psychology, value: @wrestler.psychology %>
    <%= f.hidden_field :name, value: @wrestler.name %>
    <%= f.hidden_field :execution, value: @wrestler.execution %>
    <%= f.hidden_field :score, value: @wrestler.score %>
    <%= f.hidden_field :star_rating, value: @wrestler.star_rating %>
    <%= f.submit 'Save Wrestler' %>
<% end %>